### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [kengo41/local_gourmet#56]
MVPリリースお疲れ様でした！
LGTMです
issueコメントで本リリースまでのスケジュールを教えてください 🙇 

以下にレビュー内容を記載します(全体的によくできており、細かいところの指摘になっています)

## タイポ
プロフールになってしまっていました
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/86c3a3333768d570935bf360a932d7df.png)](https://startup-technology.gyazo.com/86c3a3333768d570935bf360a932d7df)

## お店検索機能
お店検索画面を開くとお店が見つかりませんと出てしまっていてこの周辺にはお店がないのかなと勘違いしてしまうかなと思いますので文言を変更すると良いかなと思いました
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/c092590dd10dfd2dba0c9b39112b7738.jpg)](https://startup-technology.gyazo.com/c092590dd10dfd2dba0c9b39112b7738)

**Comment by kengo41** [comment]
お返事遅くなり申し訳ございません🙇
レビューありがとうございます！
「お店が見つかりません」の文言についてはフラッシュメッセージで表示するように変更いたしました！
本リリースまでのスケジュールについてですが、月末の1/31までのリリースを予定しております。

**Comment by kenchasonakai** [comment]
ご返答ありがとうございます！
スケジュールの件も承知いたしました 🙌
